#!/usr/bin/env python3

"""
Created on 2 Jan 2026

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_control

DESCRIPTION
A service to raise cron events according to model time
Note that in --run mode, the utility runs forever.

SYNOPSIS
mrcs_cron [-h] [-i INDENT] [-v] [--version] [-t] [-c] (-r | -s)

EXAMPLES
mrcs_cron --verbose --run-save --test

SEE ALSO
mrcs_clock_manager
mrcs_crontab
"""

import sys

from mrcs_control.cli.args.cron_args import CronArgs
from mrcs_control.operations.time.cron_node import CronNode
from mrcs_core.data.json import JSONify
from mrcs_core.sys.logging import Logging


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    # ----------------------------------------------------------------------------------------------------------------

    args = CronArgs('a service to raise cron events according to model time')

    Logging.config('mrcs_cron', verbose=args.verbose)
    logger = Logging.getLogger()
    logger.info(f'args: {args}')
    logger.info(f'mode: {args.mode.value}')

    # ----------------------------------------------------------------------------------------------------------------

    try:
        cron = CronNode(args.mode.value, args.save_model_time)
        logger.info(f'cron: {cron}')

        if args.clean:
            cron.clean()

        if args.list:
            jobs = cron.list()
            print(JSONify.dumps(list(jobs), indent=args.indent))
            logger.info(f'found {len(jobs)} items.')

        if args.run or args.run_save:
            cron.run()


    # ----------------------------------------------------------------------------------------------------------------

    except KeyboardInterrupt:
        print(file=sys.stderr)
