#!/usr/bin/env python3

"""
Created on 2 Jan 2026

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_control

DESCRIPTION
A service to raise cron events according to model time

A --drain function is available - this drains the queue used by mrcs_control_cron before any other functions
are invoked. The function is useful if problematic messages have been published to the queue.

Note that in --run mode, the utility runs forever.

SYNOPSIS
mrcs_control_cron [-h] [-i INDENT] [-v] [--version] [-t] [-d] [-c] [-l | -r | -s]

EXAMPLES
mrcs_control_cron --verbose --test --run-save

FILES
~/MRCS/conf/model_time.json

SEE ALSO
mrcs_clock_manager
mrcs_crontab
"""

import sys

from mrcs_control.cli.args.cron_args import CronArgs
from mrcs_control.operations.time.cron_node import CronNode
from mrcs_core.data.json import JSONify
from mrcs_core.sys.logging import Logging


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    node = None

    # ----------------------------------------------------------------------------------------------------------------

    args = CronArgs('a service to raise cron events according to model time')

    Logging.config('mrcs_control_cron', verbose=args.verbose)
    logger = Logging.getLogger()
    logger.info(f'args: {args}')
    logger.info(f'mode: {args.mode.value}')

    # ----------------------------------------------------------------------------------------------------------------

    try:
        node = CronNode(args.mode.value, args.save_model_time)
        logger.info(f'node: {node}')

        if args.drain:
            node.drain()

        if args.clean:
            node.clean()

        if args.list:
            jobs = node.find_all()
            print(JSONify.dumps(list(jobs), indent=args.indent))
            logger.info(f'found {len(jobs)} items.')

        if args.run or args.run_save:
            node.run()


    # ----------------------------------------------------------------------------------------------------------------

    except KeyboardInterrupt:
        print(file=sys.stderr)

    finally:
        if node is not None:
            node.close()
