#!/usr/bin/env python3

"""
Created on 31 Jul 2026

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_control

DESCRIPTION
A service providing an interface between a control router station and the messaging system. The control router process
accepts command messages on CRT.*.1 and publishes report messages on CRT.*.1.
In --verbose mode, the reports are written to the logger.

The control router process runs a keep-alive, periodically interrogating the control router station.  If the station
is not available, incomming messages will remain on the queue until the station is available again. Note that -
in the current regime - command messages may be lost during the interval between the station being unavailable and its
unavailability being established.

The mrcs_z21_conf utility should be used before the first use of this utility in order to establish a control router
configuration.

Note that the utility runs forever.

SYNOPSIS
mrcs_control_router [-h] [-i INDENT] [-v] [--version] [-t] (-r | -s)

EXAMPLES
mrcs_control_router -t -r -v

FILES
~/MRCS/conf/control_router_conf.json

SEE ALSO
mrcs_control_z21
mrcs_control_z21_conf
"""

import sys

from mrcs_control.cli.args.router_args import RouterArgs
from mrcs_control.operations.control_router.control_router_node import ControlRouterNode
from mrcs_core.data.json import JSONify
from mrcs_core.equipment.control_router.control_router_conf import ControlRouterConf
from mrcs_core.sys.host import Host
from mrcs_core.sys.logging import Logging


# --------------------------------------------------------------------------------------------------------------------

def on_message(message):
    if args.verbose:
        print(JSONify.dumps(message, indent=args.indent))


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    router = None

    # ----------------------------------------------------------------------------------------------------------------

    args = RouterArgs('a service providing the interface between a control router and the messaging system')

    Logging.config('mrcs_control_router', verbose=args.verbose)  # level=logging.DEBUG / verbose=args.verbose
    logger = Logging.getLogger()
    logger.info(f'args: {args}')
    logger.info(f'mode: {args.mode.value}')

    conf = ControlRouterConf.load(Host)
    if conf is None:
        logger.error('no configuration found - use mrcs_control_z21_conf to create one.')
        exit(1)

    # ----------------------------------------------------------------------------------------------------------------

    try:
        router = ControlRouterNode(args.mode.value, conf, on_message=on_message)
        logger.info(f'router: {router}')

        if args.run:
            router.run()


    # ----------------------------------------------------------------------------------------------------------------

    except KeyboardInterrupt:
        print(file=sys.stderr)

    finally:
        if router is not None:
            # noinspection unresolved-references
            router.close()
