#!/usr/bin/env python3

"""
Created on 1 Jan 2026

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_control

DESCRIPTION
A service to record cron event schedules according to model time

A --drain function is available - this drains the queue used by mrcs_control_crontab before any other functions
are invoked. The function is useful if problematic messages have been published to the queue.

Note that in --subscribe mode, the utility runs forever.

Test with:
cli/mrcs_publisher -vti4 -t CRN -n 3 -m '{"event_id": "abc", "on": "2026-01-03T06:00:00.000"}'

SYNOPSIS
mrcs_control_crontab [-h] [-i INDENT] [-v] [--version] [-t] [-d] (-c | -l | -s)

EXAMPLES
mrcs_control_crontab --verbose --subscribe --test

SEE ALSO
mrcs_clock_manager
mrcs_cron
"""

import sys

from mrcs_control.cli.args.crontab_args import CrontabArgs
from mrcs_control.operations.time.crontab_node import CrontabNode
from mrcs_core.data.json import JSONify
from mrcs_core.sys.logging import Logging


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    # ----------------------------------------------------------------------------------------------------------------

    args = CrontabArgs('a service to record cron event schedules according to model time')

    Logging.config('mrcs_control_crontab', verbose=args.verbose)
    logger = Logging.getLogger()
    logger.info(f'args: {args}')
    logger.info(f'mode: {args.mode.value}')

    # ----------------------------------------------------------------------------------------------------------------

    try:
        crontab = CrontabNode(args.mode.value)
        logger.info(f'crontab: {crontab}')

        if args.drain:
            crontab.drain()

        if args.clean:
            crontab.clean()
            exit(0)

        if args.list:
            jobs = list(crontab.find_all())
            print(JSONify.dumps(jobs, indent=args.indent))
            logger.info(f'found {len(jobs)} items.')
            exit(0)

        if args.subscribe:
            crontab.subscribe()
            exit(0)


    # ----------------------------------------------------------------------------------------------------------------

    except KeyboardInterrupt:
        print(file=sys.stderr)
