#!/usr/bin/env python3

"""
Created on 17 Nov 2025

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_control

DESCRIPTION
A tool to manage message broker exchanges and queues. The --test argument specifies which exchanges and queues are
being managed.

Note that, if an exchange is selected for deletion, all queues bound to it are deleted.

It is essential to delete a queue if a routing key has changed - the queue is normally durable, and so are its
routing keys! No process may be attached to the broker when deleting takes place.

SYNOPSIS
mrcs_control_broker [-h] [-i INDENT] [-v] [--version] [-t] (-e | -q) [-d DELETE | -z]

EXAMPLES
mrcs_control_broker -t -v -i4 -e -d mrcs.test.CRN.*.002
mrcs_control_broker -v -i4 -e -z
"""

import sys

from pika.exceptions import AMQPError

from mrcs_control.cli.args.broker_args import BrokerArgs
from mrcs_control.messaging.broker import Broker
from mrcs_control.messaging.mq_client import MQManager
from mrcs_core.data.json import JSONify
from mrcs_core.sys.logging import Logging


# --------------------------------------------------------------------------------------------------------------------

def find_filtered():
    items = broker.list_exchanges() if args.exchange else broker.list_queues()
    return args.mode.value.broker_filter(items)


def delete(item_name: str):
    if manager is None:
        return

    if args.queue:
        manager.queue_delete(item_name)
        return

    if args.exchange:
        for queue in broker.list_queues():
            manager.queue_delete(queue.name)

        manager.exchange_delete(item_name)


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    manager = None

    # ----------------------------------------------------------------------------------------------------------------

    args = BrokerArgs('a tool for managing message broker exchanges and queues')

    Logging.config('mrcs_control_broker', verbose=args.verbose)  # verbose=args.verbose / level=logging.DEBUG
    logger = Logging.getLogger()
    logger.info(f'args: {args}')
    logger.info(f'mode: {args.mode.value}')

    # ----------------------------------------------------------------------------------------------------------------

    try:
        broker = Broker.construct()
        logger.info(f'broker: {broker}')

        if args.delete:
            if args.delete not in [item.name for item in find_filtered()]:
                logger.error(f'item "{args.delete}" not present.')
                exit(2)

            manager = MQManager()
            manager.connect()

            delete(args.delete)

        if args.erase:
            manager = MQManager()
            manager.connect()

            for item in find_filtered():
                delete(item.name)

        if not args.delete and not args.erase:
            filtered_items = find_filtered()
            print(JSONify.dumps(filtered_items, indent=args.indent))

            if args.queue:
                logger.info(f'found {len(filtered_items)} items.')


    # ----------------------------------------------------------------------------------------------------------------

    except AMQPError as exc:
        logger.error(exc)
        exit(1)

    except KeyboardInterrupt:
        print(file=sys.stderr)

    finally:
        if manager:
            manager.close()
