#!/usr/bin/env python3

"""
Created on 13 Sep 2026

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_control

DESCRIPTION
A utility to interrogate layouts.

SYNOPSIS
mrcs_control_layout [-h] [-i INDENT] [-v] [--version] [-t] [-p HEADING START END] layout

EXAMPLES
mrcs_control_layout -v -i4 -p UP BS01/SG01 BS04/SG01 shelf_001
"""

import sys

from mrcs_control.cli.args.layout_args import LayoutArgs
from mrcs_control.cli.internal.topic_subscriber_node import TopicSubscriberNode
from mrcs_control.operations.track.track_node import TrackNode
from mrcs_control.operations.track.track_node_identity import TrackNodeCommand
from mrcs_core.data.equipment_identity import EquipmentIdentifier, EquipmentType
from mrcs_core.data.json import JSONify
from mrcs_core.equipment.turnout.turnout_configuration import TurnoutConfiguration
from mrcs_core.equipment.turnout.turnout_status import TurnoutStatus
from mrcs_core.inventory.layout.layout import Layout
from mrcs_core.messaging.message import Message
from mrcs_core.messaging.routing_key import PublicationRoutingKey
from mrcs_core.sys.host import Host
from mrcs_core.sys.logging import Logging


# --------------------------------------------------------------------------------------------------------------------

def on_message(message):
    global turnouts

    turnouts = [TurnoutStatus.construct_from_jdict(jdict) for jdict in message.body]
    node.request_shutdown()


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    turnouts = []

    # ----------------------------------------------------------------------------------------------------------------

    args = LayoutArgs('utility to interrogate layouts')

    Logging.config('mrcs_control_layout', verbose=args.verbose)  # verbose=args.verbose / level=logging.DEBUG
    logger = Logging.getLogger()
    logger.info(f'args: {args}')

    this_id = EquipmentIdentifier(EquipmentType.TST, None, 2)

    publication_routing_key = PublicationRoutingKey(this_id, TrackNode.id())
    subscription_routing_key = publication_routing_key.reversed()

    # ----------------------------------------------------------------------------------------------------------------

    layout = Layout.load(Host, name=args.layout)

    try:
        layout.validate()
    except Exception as exc:
        logger.error(exc)
        exit(1)

    if args.path:
        locations = layout.locations

        if args.path_start not in locations:
            logger.error(f'The start location {args.path_start.shortform} is not in the layout.')
            exit(2)

        if args.path_end not in locations:
            logger.error(f'The end location {args.path_end.shortform} is not in the layout.')
            exit(2)

        TopicSubscriberNode.set_id(this_id)
        TopicSubscriberNode.set_subscription_routing_keys([subscription_routing_key])

        node = TopicSubscriberNode.construct_node(args.mode.value, on_message)
        logger.info(f'node: {node}')

        # start subscriber...
        command_message = Message(publication_routing_key, TrackNodeCommand.FIND_ALL_TURNOUTS)
        node.run(initial_publication=command_message)

        # subscriber has now stopped...
        config = TurnoutConfiguration.construct_from_turnouts(*turnouts)

        try:
            path = layout.path(config, args.path_heading, args.path_start, args.path_end)
            print(JSONify.dumps(path, indent=args.indent))

            logger.info(f'total length: {path.total_length}')
        except ValueError as exc:
            print(exc, file=sys.stderr)

    # ----------------------------------------------------------------------------------------------------------------
