#!/usr/bin/env python3

"""
Created on 17 Nov 2025

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_control

DESCRIPTION
A service to record all inter-process messages.
Recorder components follow system time, not model time.

Note that in --subscribe mode, the utility runs forever.

SYNOPSIS
mrcs_recorder [-h] [-i INDENT] [-v] [--version] [-t] [-c] (-r REPORT | -s)

EXAMPLES
mrcs_recorder --verbose --test --clean --subscribe
"""

import sys

from mrcs_control.cli.args.recorder_args import RecorderArgs
from mrcs_control.operations.recorder.message_recorder_node import MessageRecorderNode

from mrcs_core.data.json import JSONify
from mrcs_core.sys.logging import Logging


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    # ----------------------------------------------------------------------------------------------------------------

    args = RecorderArgs('a service to record all inter-process messages')

    Logging.config('mrcs_recorder', verbose=args.verbose)
    logger = Logging.getLogger()
    logger.info(f'args: {args}')
    logger.info(f'mode: {args.mode.value}')


    # ----------------------------------------------------------------------------------------------------------------

    try:
        recorder_node = MessageRecorderNode.construct(args.mode)
        logger.info(f'recorder_node: {recorder_node}')

        if args.clean:
            recorder_node.clean()

        if args.report is not None:
            records = list(recorder_node.find_latest(args.report))
            print(JSONify.dumps(records, indent=args.indent))

            logger.info(f'found {len(records)} items.')

        if args.subscribe:
            recorder_node.subscribe()


    # ----------------------------------------------------------------------------------------------------------------

    except KeyboardInterrupt:
        print(file=sys.stderr)
