#!/usr/bin/env python3

"""
Created on 6 Jun 2026

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_control

DESCRIPTION
A utility to excercise a Roco Z21 control router station. This utility is provided for test purposes - the interface
to the Z21 is provided by the mrcs_control_router messaging interface in live environments.

The mrcs_z21_conf utility should be used before the first use of this utility in order to establish a control router
configuration.

SYNOPSIS
mrcs_control_z21 [-h] [-i INDENT] [-v] [--version] [-m | -s | -p POWER | -t TURNOUT TURNOUT]

EXAMPLES
mrcs_control_router
mrcs_control_z21_conf

FILES
~/MRCS/conf/z21_conf.json

SEE ALSO
mrcs_control_router
mrcs_control_z21_conf
"""

import asyncio
import logging
import sys

from mrcs_control.cli.args.z21_control_args import Z21ControlArgs
from mrcs_control.dcc.z21.command.station import Z21Station
from mrcs_core.data.json import JSONable, JSONify
from mrcs_core.equipment.control_router.control_router_conf import ControlRouterConf
from mrcs_core.sys.host import Host
from mrcs_core.sys.logging import Logging


# TODO: implement a keep-alive, like ControlRouterNode
# --------------------------------------------------------------------------------------------------------------------

def mrcs_control_on_dataset(report: JSONable):
    print(JSONify.dumps(report))
    # if args.monitor:
    #     print(JSONify.dumps(report))
    #     return
    #
    # if isinstance(report, args.command.report_type):
    #     print(JSONify.dumps(report))
    #     exit(0)


def mrcs_control_on_connection_lost(exc: Exception):
    if exc:
        logger.warning(f'connection lost - exc: {exc}')  # TODO: when does this happen?


async def monitor():
    async with await Z21Station.connect(conf, mrcs_control_on_dataset, mrcs_control_on_connection_lost) as station:
        logger.info(f'station: {station}')

        await station.set_broadcast_flags(conf.subscription)

        if args.has_command:
            command = args.command
            print(f'command: {JSONify.dumps(command)}')
            await station.send_command(command)
            # if command.report_type is None:
            #     exit(0)

        while True:
            await asyncio.sleep(1)  # TODO: test connection here?


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    # ----------------------------------------------------------------------------------------------------------------

    args = Z21ControlArgs('a utility to excercise a Roco Z21 control router station')

    Logging.config('mrcs_control_z21', level=logging.DEBUG)  # level=logging.DEBUG / verbose=args.verbose
    logger = Logging.getLogger()
    logger.info(f'args: {args}')

    conf = ControlRouterConf.load(Host)
    if conf is None:
        logger.error('no configuration found - use mrcs_control_z21_conf to create one.')
        exit(1)

    logger.info(f'conf: {conf}')

    # ----------------------------------------------------------------------------------------------------------------

    try:
        asyncio.run(monitor())

    # ----------------------------------------------------------------------------------------------------------------

    except KeyboardInterrupt:
        print(file=sys.stderr)
