#!/usr/bin/env python3

"""
Created on 6 Jun 2026

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_control

DESCRIPTION
A utility to excercise a Roco Z21 control station. The mrcs_z21_conf utility should be used before the first use of
this utility in order to establish an access control configuration.

SYNOPSIS
mrcs_z21_control [-h] [-i INDENT] [-v] [--version] [-m | -s | -p POWER | -t TURNOUT TURNOUT]

EXAMPLES
mrcs_z21_control -p 1
mrcs_z21_control -t 3 0

FILES
~/MRCS/conf/z21_conf.json

SEE ALSO
mrcs_z21_conf
"""

import asyncio
import logging
import sys
import time

from mrcs_control.cli.args.z21_control_args import Z21ControlArgs
from mrcs_control.dcc.z21.command.station import Z21Station
from mrcs_core.data.json import JSONable, JSONify
from mrcs_core.equipment.control_router.control_router_conf import ControlRouterConf
from mrcs_core.sys.host import Host
from mrcs_core.sys.logging import Logging


# --------------------------------------------------------------------------------------------------------------------

def mrcs_control_on_dataset(report: JSONable):
    if args.monitor:
        print(JSONify.dumps(report))
        return

    if isinstance(report, args.command.report_type):
        print(JSONify.dumps(report))
        exit(0)


def mrcs_control_on_connection_lost(exc: Exception):
    if exc:
        logger.warning(f'connection lost - exc: {exc}')


async def monitor():
    async with await Z21Station.connect(conf, mrcs_control_on_dataset, mrcs_control_on_connection_lost) as station:
        time.sleep(0.1)

        logger.info(f'station: {station}')

        await station.set_broadcast_flags(conf.subscription)
        time.sleep(0.1)

        if args.has_command:
            command = args.command
            await station.send_command(command)
            if command.report_type is None:
                exit(0)

        while True:
            await asyncio.sleep(1)


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    # ----------------------------------------------------------------------------------------------------------------

    args = Z21ControlArgs('a utility to excercise a Roco Z21 control station')

    Logging.config('mrcs_z21_control', level=logging.DEBUG)
    logger = Logging.getLogger()
    logger.info(f'args: {args}')

    conf = ControlRouterConf.load(Host)
    if conf is None:
        logger.error('no configuration found - use mrcs_z21_conf to create one.')
        exit(1)

    logger.info(f'conf: {conf}')

    # ----------------------------------------------------------------------------------------------------------------

    try:
        asyncio.run(monitor())

    # ----------------------------------------------------------------------------------------------------------------

    except KeyboardInterrupt:
        print(file=sys.stderr)
