#!/usr/bin/env python3

"""
Created on 1 Aug 2026

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_control

DESCRIPTION
A tool for subscribing to topics.
Multiple publisher sources can be specified. Messages are written to stdout in json format.
At least one source must be specified. The default message recipient (target) is '*.*.*'.

Warning: if the '*' character is used in the source or target, then the parameter should be enclosed in quotation marks.

SYNOPSIS
mrcs_control_subscriber [-h] [-i INDENT] [-v] [--version] [-t] [-r RECIPIENT] -s SOURCE [SOURCE ...]

EXAMPLES
mrcs_control_subscriber -t -v   -s 'TST.*.002' -r 'TST.*.003'
"""

import sys

from mrcs_control.cli.args.subscriber_args import SubscriberArgs
from mrcs_control.cli.internal.topic_subscriber_node import TopicSubscriberNode
from mrcs_core.data.equipment_identity import EquipmentFilter
from mrcs_core.data.json import JSONify
from mrcs_core.messaging.routing_key import SubscriptionRoutingKey
from mrcs_core.sys.logging import Logging


# --------------------------------------------------------------------------------------------------------------------

def on_message(message):
    print(JSONify.dumps(message, indent=args.indent))


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    subscriber = None

    # ----------------------------------------------------------------------------------------------------------------

    args = SubscriberArgs('a tool for subscribing to topics')

    Logging.config('mrcs_control_subscriber', verbose=args.verbose)
    logger = Logging.getLogger()
    logger.info(f'args: {args}')
    logger.info(f'mode: {args.mode.value}')

    if args.recipient == '__init__.py':  # the result of unquoted '*'
        logger.error(f'the source is invalid.')
        exit(2)

    try:
        target = EquipmentFilter.construct_from_jdict(args.recipient)
    except ValueError:
        logger.error(f'the recipient {args.recipient} is invalid.')
        exit(2)

    sources = []
    for source in args.sources:
        if source == '__init__.py':  # the result of unquoted *
            logger.error(f'the source is invalid.')
            exit(2)

        try:
            sources.append(EquipmentFilter.construct_from_jdict(source))
        except ValueError:
            logger.error(f'the source {source} is invalid.')
            exit(2)

    subscriptions = [SubscriptionRoutingKey(source, target) for source in sources]

    # ----------------------------------------------------------------------------------------------------------------

    try:
        TopicSubscriberNode.set_id(target)
        TopicSubscriberNode.set_subscription_routing_keys(subscriptions)

        subscriber = TopicSubscriberNode.construct_node(args.mode.value, on_message)
        logger.info(subscriber)

        subscriber.subscribe()


    # ----------------------------------------------------------------------------------------------------------------

    finally:
        if args.sources:
            print(file=sys.stderr)

        if subscriber is not None:
            # noinspection unresolved-references
            subscriber.close()
