#!/usr/bin/env python3

"""
Created on 13 Sep 2026

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_control

DESCRIPTION
A utility for navigating layouts.

The utility requires the backend services to be running in order to determine the layout's current turnout positions.

SYNOPSIS
usage: mrcs_control_layout [-h] [-i INDENT] [-v] [--version] [-t] (-l | -sl LAYOUT | -br [BLK[.SEG]] | -sr [STN[.PLT]]
 | -sp HEADING BLK1.SEG1 BLK2.SEG2 | -pp HEADING STN1.PLT1 STN2.PLT2)

EXAMPLES
mrcs_control_layout -v -i4 -l
mrcs_control_layout -v -i4 -br BS02
mrcs_control_layout -v -i4 -sr Beta
mrcs_control_layout -v -i4 -sp UP BS01.SG01 BS07.SG01
mrcs_control_layout -v -i4 -pp UP Alpha.1 Beta.1
"""

import sys

from mrcs_control.cli.args.layout_args import LayoutArgs
from mrcs_control.cli.internal.turnout_configuration_finder import TurnoutConfigurationFinder
from mrcs_core.data.equipment_identity import EquipmentIdentifier, EquipmentType
from mrcs_core.data.json import JSONify
from mrcs_core.inventory.layout.layout import Layout
from mrcs_core.inventory.layout.layout_conf import LayoutConf
from mrcs_core.sys.host import Host
from mrcs_core.sys.logging import Logging


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    layout = None
    config = None
    path = None

    # ----------------------------------------------------------------------------------------------------------------

    args = LayoutArgs('a utility for navigating layouts')

    Logging.config('mrcs_control_layout', verbose=args.verbose)  # verbose=args.verbose / level=logging.DEBUG
    logger = Logging.getLogger()
    logger.info(f'args: {args}')

    this_id = EquipmentIdentifier(EquipmentType.TST, None, 2)

    # ----------------------------------------------------------------------------------------------------------------

    if args.list:
        layouts = Layout.list(Host)
        print(JSONify.dumps(layouts, indent=args.indent))
        exit(0)

    if args.set_selected_layout:
        if args.set_selected_layout not in Layout.list(Host):  # TODO: this code could go in LayoutConf?
            logger.error(f'Layout {args.set_selected_layout} is not known.')
            exit(2)

        conf = LayoutConf(args.set_selected_layout)
        conf.save(Host)
        exit(0)

        # ----------------------------------------------------------------------------------------------------------------

    layout = LayoutConf.load_selected_layout(Host)

    # try:
    #     layout = LayoutConf.load_selected_layout(Host)
    # except Exception as exc:
    #     logger.error(f'{exc.__class__.__name__}:{exc}')
    #     exit(2)

    if layout is None:
        logger.error(f'No layout is selected. Use mrcs_control_layout --set-selected-layout to set one.')
        exit(1)

    logger.info(f'layout: {layout.label}')

    # ----------------------------------------------------------------------------------------------------------------

    if args.block_report:
        try:
            blocks = layout.block_report(args.report_node_block, args.report_node_segment)
        except KeyError as exc:
            logger.error(f'The node {exc.args[0]} could not be found.')
            exit(2)

        print(JSONify.dumps(blocks, indent=args.indent))
        exit(0)

    if args.station_report:
        try:
            stations = layout.station_report(args.report_node_station, args.report_node_platform)
        except KeyError as exc:
            logger.error(f'The node {exc.args[0]} could not be found.')
            exit(2)

        print(JSONify.dumps(stations, indent=args.indent))
        exit(0)

    # ----------------------------------------------------------------------------------------------------------------

    try:
        layout.validate()
    except Exception as exc:
        logger.error(exc)
        exit(1)

    finder = TurnoutConfigurationFinder(this_id)
    config = finder.find(args.mode.value)

    if args.segment_path:
        locations = layout.segment_locations

        if args.segment_path_start not in locations:
            logger.error(f'The start location {args.segment_path_start.dot_path} is not in the layout.')
            exit(2)

        if args.segment_path_end not in locations:
            logger.error(f'The end location {args.segment_path_end.dot_path} is not in the layout.')
            exit(2)

        try:
            path = layout.segment_route(config, args.path_heading, args.segment_path_start, args.segment_path_end)
        except ValueError as exc:
            print(exc, file=sys.stderr)
            exit(1)

    if args.platform_path:
        locations = layout.platform_locations

        if args.platform_path_start not in locations:
            logger.error(f'The start platform {args.platform_path_start.dot_path} is not in the layout.')
            exit(2)

        if args.platform_path_end not in locations:
            logger.error(f'The end platform {args.platform_path_end.dot_path} is not in the layout.')
            exit(2)

        try:
            path = layout.platform_route(config, args.path_heading, args.platform_path_start, args.platform_path_end)
        except ValueError as exc:
            print(exc, file=sys.stderr)
            exit(1)

    if path is not None:
        print(JSONify.dumps(path, indent=args.indent))
        # noinspection unresolved-references
        logger.info(f'total length: {path.total_length}')
