#!/usr/bin/env python3

"""
Created on 6 Jun 2026

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_control

DESCRIPTION
A utility to excercise a Roco Z21 control router station directly. This utility is provided for test purposes -
the interface to the Z21 is provided by the mrcs_control_router messaging interface in live environments.

Note that the turnout address is 1-based, not 0-based.

The mrcs_z21_conf utility should be used before the first use of this utility in order to establish a control router
configuration.

SYNOPSIS
mrcs_control_z21 [-h] [-i INDENT] [-v] [--version] [-m] [-r | -p {0,1} | -u ADDR POSITION |
-d ADDR | -g ADDR | -s ADDR DIRECTION SPEED]

EXAMPLES
mrcs_control_z21 -v -m
mrcs_control_z21 -v -p 0

FILES
~/MRCS/conf/z21_conf.json

SEE ALSO
mrcs_control_command
mrcs_control_publisher
mrcs_control_subscriber
"""

import asyncio
import sys

from mrcs_control.cli.args.z21_args import Z21Args
from mrcs_control.dcc.z21.command.command import Command
from mrcs_control.dcc.z21.command.station import Station
from mrcs_core.data.json import JSONable, JSONify
from mrcs_core.equipment.control_router.control_router_conf import ControlRouterConf
from mrcs_core.sys.host import Host
from mrcs_core.sys.logging import Logging


# --------------------------------------------------------------------------------------------------------------------


def mrcs_control_on_dataset(report: JSONable):
    if args.monitor:
        print(JSONify.dumps(report))
        return

    if args.command is None or args.command.report_type is None:
        return

    if isinstance(report, args.command.report_type):
        print(JSONify.dumps(report))
        exit(0)


def mrcs_control_on_connection_lost(ex: Exception):
    if ex:
        logger.warning(f'connection lost: {ex}')


async def monitor():
    station = Station(conf, mrcs_control_on_dataset, mrcs_control_on_connection_lost)
    await station.connect()
    logger.info(f'station: {station}')

    async with station:
        await station.send_command(Command.lan_set_broadcast_flags(conf.subscription))

        if args.has_command:
            command = args.command
            await station.send_command(command)
            if command.report_type is None:
                return

        while True:
            await asyncio.sleep(20)
            await station.send_command(Command.lan_set_broadcast_flags(conf.subscription))


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    # ----------------------------------------------------------------------------------------------------------------

    args = Z21Args('a utility to excercise a Roco Z21 control router')

    Logging.config('mrcs_control_z21', verbose=args.verbose)  # level=logging.DEBUG / verbose=args.verbose
    logger = Logging.getLogger()
    logger.info(f'args: {args}')

    conf = ControlRouterConf.load(Host)
    if conf is None:
        logger.error('no configuration found - use mrcs_control_z21_conf to create one.')
        exit(1)

    logger.info(f'conf: {conf}')

    # ----------------------------------------------------------------------------------------------------------------

    try:
        asyncio.run(monitor())

    # ----------------------------------------------------------------------------------------------------------------

    except KeyboardInterrupt:
        print(file=sys.stderr)

    except RuntimeError as exc:
        logger.error(f'{type(exc).__name__}: {exc}')
        sys.exit(1)

    except Exception:
        logger.exception('unexpected failure')
        sys.exit(1)
