#!/usr/bin/env python3

"""
Created on 13 Sep 2026

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_control

DESCRIPTION
A utility for navigating layouts.

The utility requires the backend services to be running in order to determine the layout's turnout positions.

SYNOPSIS
mrcs_control_layout [-h] [-i INDENT] [-v] [--version] [-t] (-l | -r LAYOUT | -s LAYOUT |
-g HEADING START END | -p HEADING START END)

EXAMPLES
mrcs_control_layout -v -i4 -l
mrcs_control_layout -v -i4 -g UP BS01/SG01 BS04/SG01 shelf_001
mrcs_control_layout -v -i4 -p UP Alpha/1 Beta/1
"""

import sys

from mrcs_control.cli.args.layout_args import LayoutArgs
from mrcs_control.cli.internal.turnout_configuration_finder import TurnoutConfigurationFinder
from mrcs_core.data.equipment_identity import EquipmentIdentifier, EquipmentType
from mrcs_core.data.json import JSONify
from mrcs_core.inventory.layout.layout import Layout
from mrcs_core.inventory.layout.layout_conf import LayoutConf
from mrcs_core.sys.host import Host
from mrcs_core.sys.logging import Logging


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    layout = None
    config = None
    path = None

    # ----------------------------------------------------------------------------------------------------------------

    args = LayoutArgs('a utility for navigating layouts')

    Logging.config('mrcs_control_layout', verbose=args.verbose)  # verbose=args.verbose / level=logging.DEBUG
    logger = Logging.getLogger()
    logger.info(f'args: {args}')

    this_id = EquipmentIdentifier(EquipmentType.TST, None, 2)

    # ----------------------------------------------------------------------------------------------------------------

    if args.list:
        layouts = Layout.list(Host)
        print(JSONify.dumps(layouts, indent=args.indent))
        exit(0)

    if args.report:
        layout = Layout.load(Host, args.report)

        if layout is None:
            logger.error(f'Layout {args.report} is not known.')
            exit(2)

        print(JSONify.dumps(layout, indent=args.indent))
        exit(0)

    if args.set_selected_layout:
        if args.set_selected_layout not in Layout.list(Host):
            logger.error(f'Layout {args.set_selected_layout} is not known.')
            exit(2)

        conf = LayoutConf(args.set_selected_layout)
        conf.save(Host)
        exit(0)

    # ----------------------------------------------------------------------------------------------------------------

    try:
        layout = LayoutConf.load_selected_layout(Host)
    except Exception as exc:
        logger.error(exc)
        exit(2)

    if layout is None:
        logger.error(f'No layout is selected. Use mrcs_control_layout --set-selected-layout to set one.')
        exit(1)

    logger.info(f'layout: {layout.label}')

    try:
        layout.validate()
    except Exception as exc:
        logger.error(exc)
        exit(1)

    finder = TurnoutConfigurationFinder(this_id)
    config = finder.find(args.mode.value)

    if args.segment_path:
        locations = layout.locations

        if args.segment_path_start not in locations:
            logger.error(f'The start location {args.segment_path_start.shortform} is not in the layout.')
            exit(2)

        if args.segment_path_end not in locations:
            logger.error(f'The end location {args.segment_path_end.shortform} is not in the layout.')
            exit(2)

        try:
            path = layout.segment_path(config, args.path_heading, args.segment_path_start, args.segment_path_end)
        except ValueError as exc:
            print(exc, file=sys.stderr)
            exit(1)

    if args.platform_path:
        platform_labels = layout.platform_labels

        if args.platform_path_start not in platform_labels:
            logger.error(f'The start platform {args.platform_path_start.shortform} is not in the layout.')
            exit(2)

        if args.platform_path_end not in platform_labels:
            logger.error(f'The end platform {args.platform_path_end.shortform} is not in the layout.')
            exit(2)

        try:
            path = layout.platform_path(config, args.path_heading, args.platform_path_start, args.platform_path_end)
        except ValueError as exc:
            print(exc, file=sys.stderr)
            exit(1)

    if path is not None:
        print(JSONify.dumps(path, indent=args.indent))
        # noinspection unresolved-references
        logger.info(f'total length: {path.total_length}')
