#!/usr/bin/env python3

"""
Created on 3 Jan 2026

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_control

DESCRIPTION
A service to manage the model-time clock

A model railway is typically run in its own model time. The model-time configuration will typically have its own
start datetime - for example, 06:00 on Wednesday, 1 January 1930 - and its own clock speed. The speed is a whole
number multiple of true time; the MRCS clock permits speeds of 1 to 10.

A configured clock can be paused and resumed. It is best practice to only pause the clock after operations -
together with the cron and crontab services - have stopped.

It is best practice to bring the system up in a state where the clock is paused, so that checks can be performed before
operations begin. On system start, it is possible to reload the clock with the last-recorded model time, thus enabling
operations to resume where they left off.

Note that realtime recording of the model time is done by the mrcs_cron service - if cron is not running (or cron time
recording is disabled) then the last-recorded time is not available or may be out of date.

If no clock configuration is used, then model time is true time. In this case, the clock is always running, and cannot
be paused. If a reload is performed on a clock with no configuration, then the clock gains an appropriate configuration,
with a clock speed of 1.

Options:
* configuration - report the clock configuration
* run - if the clock is stopped, start the clock at the configuration start time
* pause - if the clock is running, pause at the current time
* resume - if the clock is stopped, resume from the paused time
* reload - return to the latest-stored model datetime
* delete - delete the clock configuration

The clock configuration can be set with cli/mrcs_time utility.

SYNOPSIS
mrcs_clock [-h] [-i INDENT] [-v] [--version] [-c | -r | -p | -e | -l | -d]

SEE ALSO
mrcs_cron
cli/mrcs_time
"""

import sys

from mrcs_control.cli.args.clock_args import ClockArgs

from mrcs_core.data.json import JSONify
from mrcs_core.operations.time.clock import Clock
from mrcs_core.operations.time.clock_iso_datetime import ClockISODatetime
from mrcs_core.sys.host import Host
from mrcs_core.sys.logging import Logging


# TODO: whatever changes the clock conf, it should message this so that the API can do a ws broadcast
# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    # ----------------------------------------------------------------------------------------------------------------

    args = ClockArgs('a service to manage the model-time clock')

    Logging.config('mrcs_clock', verbose=args.verbose)
    logger = Logging.getLogger()
    logger.info(f'args: {args}')


    # ----------------------------------------------------------------------------------------------------------------

    try:
        clock = Clock.load(Host)

        if args.configuration:
            print(JSONify.dumps(clock, indent=args.indent))

        if args.run:
            if not Clock.exists(Host):
                logger.error('no clock configuration exists.')
                exit(1)

            clock.run()
            clock.save(Host)

        if args.pause:
            if not Clock.exists(Host):
                logger.error('no clock configuration exists.')
                exit(1)

            clock.pause()
            clock.save(Host)

        if args.resume:
            if not Clock.exists(Host):
                logger.error('no clock configuration exists.')
                exit(1)

            clock.resume()
            clock.save(Host)

        if args.reload:
            if not ClockISODatetime.exists(Host):
                logger.error('no stored time exists.')
                exit(1)

            stored = ClockISODatetime.load(Host)
            clock.reload(stored)
            clock.save(Host)

        if args.delete:
            Clock.delete(Host)

        if not args.configuration:
            print(JSONify.dumps(clock.now()))


    # ----------------------------------------------------------------------------------------------------------------

    except KeyboardInterrupt:
        print(file=sys.stderr)
