#!/usr/bin/env python3

"""
Created on 12 Aug 2026

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_control

DESCRIPTION
A service that manages track equipment.

SYNOPSIS
mrcs_control_track [-h] [-i INDENT] [-v] [--version] [-t] (-l {B,T,S} | -p | -r)

EXAMPLES
mrcs_control_track -t -v -r
"""

import sys

from mrcs_control.cli.args.track_args import TrackArgs
from mrcs_control.cli.inventory.block_inventory import BlockInventory
from mrcs_control.cli.inventory.turnout_inventory import TurnoutInventory
from mrcs_control.operations.track.track_node import TrackNode
from mrcs_core.data.json import JSONify
from mrcs_core.sys.host import Host
from mrcs_core.sys.logging import Logging


# --------------------------------------------------------------------------------------------------------------------

def control_track_on_message(message):
    print(JSONify.dumps(message, indent=args.indent))


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    node = None

    # ----------------------------------------------------------------------------------------------------------------

    args = TrackArgs('a service that manages track equipment')

    Logging.config('mrcs_control_track', verbose=args.verbose)  # verbose=args.verbose / level=logging.DEBUG
    logger = Logging.getLogger()
    logger.info(f'args: {args}')
    logger.info(f'mode: {args.mode.value}')

    message_handler = control_track_on_message if args.verbose else None

    # ----------------------------------------------------------------------------------------------------------------

    try:
        node = TrackNode(args.mode.value, on_message=message_handler)
        logger.info(node)

        if args.list:
            if args.list == 'B':
                equipment = node.find_all_blocks()
            elif args.list == 'T':
                equipment = node.find_all_turnouts()
            else:
                equipment = node.track_state()

            print(JSONify.dumps(equipment, indent=args.indent))

        if args.populate:
            blocks = BlockInventory.load(Host)
            turnouts = TurnoutInventory.load(Host)
            node.populate(blocks, turnouts)
            print(JSONify.dumps([blocks, turnouts], indent=args.indent))

        if args.run:
            node.subscribe()


    # ----------------------------------------------------------------------------------------------------------------

    finally:
        if args.run:
            print(file=sys.stderr)

            if node is not None:
                # noinspection unresolved-references
                node.close()
