#!/usr/bin/env python3

"""
Created on 6 Sep 2026

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_control

DESCRIPTION
A service that manages MPU telemetry

The service begins by requesting MPU configuration and decoder reports from the MPUs in its data table.

A --drain function is available - this drains the queue used by mrcs_control_track before any other functions
are invoked. The function is useful if problematic messages have been published to the queue.

SYNOPSIS
mrcs_control_telemetry [-h] [-i INDENT] [-v] [--version] [-t] [-d] [-p] (-l | -r)

EXAMPLES
mrcs_control_telemetry -v -d -r
"""

import sys

from mrcs_control.cli.args.telemetry_args import TelemetryArgs
from mrcs_control.operations.telemetry.telemetry_node import TelemetryNode
from mrcs_core.data.json import JSONify
from mrcs_core.sys.logging import Logging


# --------------------------------------------------------------------------------------------------------------------

def control_telemetry_on_message(message):
    print(JSONify.dumps(message, indent=args.indent))


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    node = None

    # ----------------------------------------------------------------------------------------------------------------

    args = TelemetryArgs('a service that manages MPU telemetry')

    Logging.config('mrcs_control_telemetry', verbose=args.verbose)  # verbose=args.verbose / level=logging.DEBUG
    logger = Logging.getLogger()
    logger.info(f'args: {args}')
    logger.info(f'mode: {args.mode.value}')

    message_handler = control_telemetry_on_message if args.verbose else None

    # ----------------------------------------------------------------------------------------------------------------

    try:
        node = TelemetryNode(args.mode.value, on_message=message_handler)
        logger.info(node)

        if args.drain:
            purged_count = node.drain()
            if purged_count is not None:
                logger.info(f'drained messages: {purged_count}')

        # if args.populate:
        #     mpus = MPUInventory.load(Host)
        #     node.populate(mpus)

        # if args.list:
        #     equipment = node.find_all_mpus()
        #     print(JSONify.dumps(equipment, indent=args.indent))

        if args.run:
            node.run()


    # ----------------------------------------------------------------------------------------------------------------

    finally:
        if args.run:
            print(file=sys.stderr)

        if node is not None:
            node.close()
